workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build

image: grupoavispa/cortex:development-latest

before_script:
  - DEBIAN_FRONTEND=noninteractive apt-get update

build:
  stage: build
  script:
    - apt-get install --no-install-recommends -y cmake g++ make git openssl libssl-dev nlohmann-json3-dev
    - mkdir build && cd build
    - cmake ..
    - make