name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: grupoavispa/cortex:development-latest
    steps:
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y cmake g++ make git openssl libssl-dev nlohmann-json3-dev

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Build project
        run: |
          mkdir -p build && cd build
          cmake ..
          make -j$(nproc)
          make install
